### ISSUE TITLE
MQTT Support

### ISSUE THREAD

**Issue by ram1505** [kalanda/esp8266-sniffer#1]
Is it possible to send the results over MQTT?

**Comment by kalanda** [comment]
As far as I know, when a wifi device is in monitor/promiscuous mode only can listen to packets and it cannot get connected to a wifi network at the same time, but, I guess that you can use two ESP8266 modules. One listening for packets and other connected to your network, and use the first one listening packets to send results to the other module by one UART line and push these results to the MQTT server from this second one.

**Comment by ram1505** [comment]
That's exactly what I'm working on. Thanks for the wonderful script. Works like charm.

**Comment by probonopd** [comment]
Or you could switch from promiscuous to normal STA mode from time to time, to send the collected data out in intervals, thus needing just 1 module.

**Comment by ram1505** [comment]
Any idea on how I can achieve this with STA mode?  I'm not that good in programming.

**Comment by probonopd** [comment]
See https://github.com/esp8266/Arduino/blob/master/doc/esp8266wifi/readme.md#station

**Comment by davidchatting** [comment]
I know this is a very old thread, but I've learnt much from your project. This scenerio with MQTT is something that my new Approximate library makes easy for both ESP32 and ESP8266 > https://github.com/davidchatting/Approximate#close-by-mqtt---make-a-connection-to-the-cloud

**Comment by kalanda** [comment]
> I know this is a very old thread, but I've learnt much from your project. This scenerio with MQTT is something that my new Approximate library makes easy for both ESP32 and ESP8266 > https://github.com/davidchatting/Approximate#close-by-mqtt---make-a-connection-to-the-cloud

@davidchatting seems like a very interesting project, glad to know you have learned something from this small one :) thanks for sharing!
