### ISSUE TITLE
Track 'n' Trace

### ISSUE THREAD

**Issue by Hairyloon** [kalanda/esp8266-sniffer#14]
If we carry an ESP sniffer around all day, and it logs all the signals that it finds, then that is some kind of record of all of the people that we have been near to, or at least, all of those who are broadcasting a WiFi (or Bluetooth?) signal, which, given the number of folk with WiFi enabled phones is probably a reasonable proportion.
While that information is not a lot of use on its own as a track and trace system, it could possibly be the beginnings of one...

**Comment by kalanda** [comment]
This area is for reporting issues. I don't see any in your comment.

**Comment by Hairyloon** [comment]
> 
> 
> This area is for reporting issues. I don't see any in your comment.

So where is the area for raising discussions?
Though if you can't see any issue in a deadly global pandemic, you're probably not worth discussing things with.
