### ISSUE TITLE
os_timer question

### ISSUE THREAD

**Issue by toncho11** [kalanda/esp8266-sniffer#15]
Hi,

What is the following code doing ?

os_timer_disarm(&channelHop_timer);
os_timer_setfn(&channelHop_timer, (os_timer_func_t *) channelHop, NULL);
os_timer_arm(&channelHop_timer, CHANNEL_HOP_INTERVAL_MS, 1);

Is this an optimization?

**Comment by kalanda** [comment]
Read the code comments in line 138, is the channel hoping. 
Changes the Wifi channel to listen every `CHANNEL_HOP_INTERVAL_MS` milliseconds.

https://github.com/kalanda/esp8266-sniffer/blob/85d946b8ed414706acd8c10cb04fe7feb61e4c73/src/main.cpp#L138-L141
