### ISSUE TITLE
Add a License

### ISSUE THREAD

**Issue by Foaly** [kalanda/esp8266-sniffer#2]
Hey!
This project looks quiet cool! I would like to use it myself and extend it a bit.
Would you mind adding a proper open source license, so I can use this without a worry?
Thank you very much!

PS: I can recommend the [zlib license](https://en.wikipedia.org/wiki/Zlib_License).

**Comment by kalanda** [comment]
Thanks, I'm glad you liked it. I prefer to use just unlicense https://github.com/kalanda/esp8266-sniffer/blob/master/LICENSE

**Comment by Foaly** [comment]
Wow thank you so much for the fast response! Public domain works even better for me 😄
I have worked with your script a bit and I might push some changes I made upstream next week.
Thanks again for the awesome script!
