### ISSUE TITLE
Search for specific MAC

### ISSUE THREAD

**Issue by PGtips240** [kalanda/esp8266-sniffer#4]
Hi,

I'd like to use this to search for a specific client MAC address.
I've spent hours trying to do it with little to no success!

Could you point me in the right direction?

Thanks

**Comment by kalanda** [comment]
@PGtips240 maybe you can check the code at this fork of my project which seems to implement some kind of mac filtering. https://github.com/GitaiQAQ/esp8266-sniffer

At this commit:
https://github.com/GitaiQAQ/esp8266-sniffer/commit/2b729cdc4936059ca1ba6b33174837a59763b529

**Comment by PGtips240** [comment]
@kalanda that's the kind of thing I was looking for, I was trying to print out the RSSI to a i2c oled and was hoping a relatively easy if statement would do it, however it doesn't seem to be working!!
Thanks for getting back to me so quickly.

**Comment by kalanda** [comment]
Great! 👍
