### ISSUE TITLE
Listening to specific SSID probe requests

### ISSUE THREAD

**Issue by Tareq-Sulaiman** [kalanda/esp8266-sniffer#8]
Hello all, this is not really an issue but rather a question.
The code works fine but I have a question about how probe requests work.
From my understanding, a WiFi client sends multiple probe requests if it is searching for multiple pre-saved SSIDs, sending one request per SSID, however, when I tried several codes including yours I get several requests per SSID with different RSSIs up to 30dB difference between them!
Also, I get several requests without any SSID so what are those for?
Could anybody elaborate more on how probe requests work (i.e : different channels, different SSIDs)?
Is there a way to only get the probe requests for a specific SSID, so I can get one request per scan, either using your code or using the WiFi event handlers from the ESP8266 arduino core(Preferably using the arduino core handlers because they work in AP mode without promiscuous mode)?

Your help is pretty much appreciated, and keep up the good work!

**Comment by kalanda** [comment]
I'm sorry @Tareq-Sulaiman but my knowledge about the WiFi isn't enough to help you.
